### PR TITLE
Get Wink hubs as a sensor

### PR DESCRIPTION
**Pull request by w1ll1am23**
Started running into issues with my Wink hub dropping offline and thought it was Home-Assistant having trouble but it has turned out to be my hub. This will create a sensor for each hub who's state is the connection status/availability of the hub. 

Also added more base device properties.

### CODE REVIEW

**Comment by w1ll1am23** [comment]
Can I disable the check on the 'Too many branches' error? Of is there a better way to correct this?

**Comment by bradsk88** [comment]
The more "correct" solution would be to move the conditionals *into* the getter functions.  You'd end up with:

```
def __get_outlets_from_powerstrip(item, api_interface, filter_key):
    if filter_key != "powerstrip_id":
        return []
    outlets = item['outlets']
    for outlet in outlets:
        if 'subscription' in item:
            outlet['subscription'] = item['subscription']
        outlet['last_reading']['connection'] = item['last_reading']['connection']
    return [build_device(outlet, api_interface) for outlet in outlets if __device_is_visible(outlet, 'outlet_id')]
```

and 

```
def get_devices_from_response_dict(response_dict, filter_key):
    """
    :rtype: list of WinkDevice
    """
    items = response_dict.get('data')

    devices = []

    keys = list(DEVICE_ID_KEYS.values())

    api_interface = WinkApiInterface()

    for item in items:
        if item.get(filter_key, None) is None:
            continue
        if not __device_is_visible(item, filter_key):
            continue

        devices.extend(__get_outlets_from_powerstrip(item, api_interface, filter_key))
        devices.extend(_get_subsensors_from_sensor_pod(item, api_interface, filter_key))
        devices.extend(__get_devices_from_piggy_bank(item, api_interface, , filter_key))
        devices.extend(__get_subsensors_from_smoke_detector(item, api_interface, , filter_key))
        if filter_key == "hub_id":
            # Could probably make a `_get_hubs()` function
            skip = False
            for key in keys:
                if key == "hub_id":
                    continue
                if item.get(key, None) is not None:
                    skip = True
            if skip:
                continue
            else:
                devices.append(build_device(item, api_interface))
        else:
            devices.append(build_device(item, api_interface))

    return devices
```

**Comment by bradsk88** [comment]
Looks good

**Comment by bradsk88** [comment]
Published

**Pull request merged**
