### PR TITLE
Add thermostat fields heat_on/cool_on

### PR DESCRIPTION
**Pull request by kpine**
I have a Sensi thermostat and I'd like track my HVAC usage in Home Assistant to see how often heating and cooling are running. Similar to fan_on ("fan_active"), these expose the "heat_active" and "cool_active" last reading fields. With these I can then patch the HA wink components to use the fields as sensors.

### CODE REVIEW

**Comment by w1ll1am23** [comment]
Hey! Thanks for this, sorry I didn't see it sooner. I think pylint keeps changing its requirements and doesn't like the current style of things. If you feel like taking a stab at the errors reported in tarvis go for it, if not I'll fix them and include your fixes in the next couple days.

**Comment by kpine** [comment]
I have some fixes, I'll go ahead and add them. Thanks.

**Comment by w1ll1am23** [comment]
@kpine I had to do some work to fix Nest cam sensors so I fixed the lint issues. This is good to go! Thanks.

python-wink 1.7.2 is now pushed to pypi so you can go ahead and do the Home Assistant work for this as well.

**Comment by w1ll1am23** [comment]
@kpine I added these to HA https://github.com/home-assistant/home-assistant/pull/11833 should be in the next release.

**Pull request merged**
