### PR TITLE
Added support for power strips

### PR DESCRIPTION
**Pull request by w1ll1am23**
Going to have a buddy of my test this later today, but mine seems to be working fine. Fixed some styling issues as well. Made all lines < 79 characters.

### CODE REVIEW

**Comment by bradsk88** [comment]
This project supports 120 character lines but I appreciate keeping lines shorter. 

I would suggest using something other than slash line breaks to accomplish this, however, because they actually tend to make code _less_ readable. 

While I won't stop this pull request from going through on that basis, know that I'll probably remove the slash breaks in the future in favor of something like better use of string templates.

**Comment by w1ll1am23** [comment]
Not a problem, if you want to suggest a different way to do it I can give it a shot. Once my friend is able to test I will update the version as well.

**Comment by bradsk88** [comment]
python's `format` function is pretty handy.

Instead of 

```
def __repr__(self):
        return "<Wink object %s %s %s>" \
               % (self.name(), self.device_id(), self.state())
```

You could write

```
def __repr__(self):
        return "<Wink object {name} {device} {state}>".format(name=self.name(),  
                                                              device=self.device_id(),  
                                                              state=self.state())
```

**Comment by w1ll1am23** [comment]
Made some changes, but we get back up above 79 lines which isn't a problem. Not sure how to make line 847 any shorter without using a \

**Comment by bradsk88** [comment]
Whether or not it's better solution is debatable but you could do this:

```
tag = "<Wink {type} name:{name} id:{device} parent id:{parent_id} state:{state}>"
return tag.format(type='Power strip outlet',
                  name=self.name(),
                  device=self.device_id(),
                  parent_id=self.parent_id(), 
                  state=self.state())
```

In this case, `tag` will probably end up as a constant that gets reused by the other types of wink objects.  But, again, I won't require you to do that for this Pull Request.

**Comment by bradsk88** [comment]
@w1ll1am23 Please rebase this branch onto master.  I pushed out some fixes that should stop this branch from raising some pylint errors.

```
git fetch
git rebase origin/master 
```

**Comment by bradsk88** [comment]
And please update the version in `setup.py` and `CHANGELOG.md`

**Comment by bradsk88** [comment]
Go ahead and toss 

```
# pylint: disable=too-many-lines
```

At the top of `pywink/__ini__.py`.  I'll refactor this file later to make it shorter.

**Comment by bradsk88** [comment]
Aside from that last pylint violation, this looks good.
If you want to toss some unit tests in, now would be the time.
I'll merge this in as soon as it's green on Travis CI.

**Pull request merged**
