### PR TITLE
Support for thermostats

### PR DESCRIPTION
**Pull request by w1ll1am23**
Still need to write test cases for this, but I have tested all of the functions I have access to on my thermostat. This addresses issue #15 

Going to need some testers on this one, so if anyone wants to volunteer, and can run a dev branch of Home-Assistant, let me know.

### CODE REVIEW

**Comment by kfgoode** [comment]
Hi, I would be more than happy to test, let me know what is needed.  I can switch over to development on HA.

**Comment by w1ll1am23** [comment]
@kfgoode Awesome! The process to get setup is somewhat complicated, but if you have any issues let me know. This PR is almost done, there aren't any issues that I know of, but I think I need to add a few more test cases.

If possible I would recommend setting up a virtual python environment. 

Then clone my HA repo https://github.com/w1ll1am23/home-assistant.git and checkout the `wink_thermostat` branch. 

Install that branch with `python3 setup.py install`
run `hass` and let it install all dependencies
once that has completed, stop hass 

clone my https://github.com/w1ll1am23/python-wink.git fork and checkout the `thermostats` branch

copy everything inside the python-wink/src/pywink/\* into {hass config dir}/deps/pywink/*

Start HA back up and it will now be using the correct version of python-wink and you should now have your thermostat in HA!

**Review by bradsk88 — APPROVED** [review]
Good stuff.  Thanks @w1ll1am23

**Comment by w1ll1am23** [comment]
@kfgoode Had a chance to test this? If not I think we can go ahead and merge @bradsk88 the best way to find any problems is going to be the most exposure, so it would be cool to get this into HA 0.32.0 which I think gets released this weekend.

**Comment by bradsk88** [comment]
@w1ll1am23 v 0.10.0 released

**Comment by asapkota** [comment]
Is there anything special one has to do to detect or use a Wink thermostart? I have HA and wink component running. It detects all of my Wink devices expect for the Thermostat. It is a generic Z-wave thermostat that is compatible with Wink GC-TBZ48. Any help is greatly appreciated. Thanks

**Comment by w1ll1am23** [comment]
@asapkota The support for Thermostats is in python-wink, but only in the dev version of Home-Assistant. It will be in the next release which should be out this weekend I believe.

**Comment by asapkota** [comment]
@w1ll1am23 Thanks. I will wait for the release.

**Pull request merged**
